name: CI Workflow

on:
    # on any commit to production branches
    push:
        branches: [production]

    # on manual trigger from the GitHub Actions UI
    workflow_dispatch:

# only one workflow can be run at a time
concurrency:
    group: ${{ github.workflow }}
    # cancel-in-progress: true

env:
    # branchname: ${{ github.ref_name }}
    # note: head_commit.message is empty when the workflow is triggered manually
    commitmsg: ${{ github.event.head_commit.message || 'manual CI trigger (dev)' }}

jobs:
    build:
        name: Install and publish build

        runs-on: ubuntu-latest

        # only run this job on specific repo (to avoid running on forks)
        # TODO: update to repo path
        if: github.repository == 'nodejs-boilertemplate/backend' 

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x
                  cache: yarn

            - name: Install dependencies
              run: yarn install --immutable

            # runs node scripts/version-increment.js in the root to increment the version number
            - name: Version increment
              run: |
                  node scripts/version-increment.js
                  
                  # define the version number as an environment variable
                  APP_VERSION=$(npm pkg get version --workspaces=false | tr -d \")

                  # set the version number as an environment variable
                  echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

            - name: Build (For Source Maps)
              run: yarn build

            - name: Create Sentry release
              uses: getsentry/action-release@v1
              env:
                  SENTRY_ORG: nodejs-boilertemplate
                  SENTRY_PROJECT: nodejs-boilertemplate-backend
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
              with:
                  sourcemaps: ./dist
                  version: ${{ env.APP_VERSION }}

            # commit the version increment change
            - name: Commit version increment changes
              run: |
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git config --global user.name "github-actions[bot]"
                  git commit -a -m "ci: version increment — ${{ env.commitmsg }}"
                  git push
